In [1]:
%matplotlib qt
from pathlib import Path
import pandas as pd
import numpy as np
import sys

from math import acos

sys.path.append(r'D:\Users\Csabi\dev\Cybathlon')

USE_ROLLING_WINDOW = False
ONLY_KONTROLL_DATA = False
FILTER_DATA = True  # 11 pix distance

# for windowing data
WINDOW_LEN = 100
WINDOW_STEP = 15

In [2]:
path = Path(r'D:\Users\Csabi\OneDrive - Pázmány Péter Katolikus Egyetem\1 Projects\Onkology')
file = path.joinpath('Összesített nyers eredmények', 'kiértékelés javított')
files = [file for file in file.rglob('*.xls') if '/DMSO/' not in str(file.as_posix()) and
         not str(file.as_posix()).endswith('/0528/A2058/1/044.xls') and
         not str(file.as_posix()).endswith('/0528/Mel JR Post/1/053.xls')]

In [3]:
from utils import calculate_init_data

def open_file(file, min_len=433):
    
    # df = pd.read_excel(file)._convert(numeric=True)
    
    dfs = pd.read_excel(file)
    # display(df)
    # df = df.astype(float)
    # display(df)

    # print(f'{file}\n{df.columns}\n\n')
    p = file.parent
    if len(p.name)==1:
        dfs['type'] = f'{p.name} uM'
    else:
        dfs['type'] = 'kontroll'
    p = p.parent
    dfs['cell line'] = p.name.removeprefix('Mel ')
    dfs.columns = [col.removeprefix(' ').removesuffix(' ') for col in dfs.columns]

    return calculate_init_data(dfs, min_len, filter_dist=FILTER_DATA)

# dfs = open_file(files[56])
# dfs[0]

In [4]:
from utils import get_features

labels = ['Cell ID unique', 'type', 'cell line']

cell_list = []
for file in files:
    cell_list.extend(open_file(file))

if USE_ROLLING_WINDOW:
    wl = WINDOW_LEN
    step = WINDOW_STEP
    win_cell_list = []
    for cdf in cell_list:
        win_cell_list.extend([w for w in cdf.rolling(window=wl, step=step) if len(w) == wl])
    clist = win_cell_list
else:
    clist = cell_list
    
df_ = pd.concat([get_features(w, labels) for w in clist], axis=1).T
df_

,total_dist,dist std,dist mean,max_disp,directionality,avg speed,msd,angle from last_mov [deg] -- std,angle from last_mov [deg] -- mav,angle from last_mov [deg] -- zc,angle from init [deg] -- std,diff angle from init [deg] -- std,diff angle from init [deg] -- mav,diff angle from init [deg] -- zc,Cell ID unique,type,cell line
0,1552.005961,12.493506,3.592606,550.138021,0.297348,0.359261,238.315834,0.0,0.0,2.0,40.834526,13.582218,1.085205,72.0,0,1 uM,A2058
1,2954.069092,16.607849,6.838123,554.637586,0.170457,0.683812,240.633322,0.0,0.0,2.0,96.197836,47.870355,9.87987,125.0,3,1 uM,A2058
2,3491.190024,19.109881,8.081458,499.909698,0.132667,0.808146,174.137192,0.0,0.0,2.0,30.267191,5.650669,1.614578,133.0,4,1 uM,A2058
3,1432.773708,11.643507,3.316606,285.105331,0.156835,0.331661,114.079129,0.0,0.0,2.0,80.227705,17.455075,2.446452,66.0,5,1 uM,A2058
4,2708.524032,18.480233,6.269732,245.876555,0.065684,0.626973,98.168256,0.0,0.0,2.0,87.76583,19.463112,3.853848,90.0,6,1 uM,A2058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3671,1773.403827,14.840244,4.105101,117.19401,0.040715,0.41051,67.972264,0.0,0.0,2.0,89.582729,34.106675,6.052095,68.0,4085,kontroll,WM983B
3672,181.737818,4.892592,0.420689,118.784997,0.42596,0.042069,17.678274,0.0,0.0,2.0,15.605693,9.970239,0.560451,8.0,4086,kontroll,WM983B
3673,489.147555,5.657191,1.132286,76.796669,0.131983,0.113229,32.198044,0.0,0.0,2.0,80.125892,23.848899,3.175773,33.0,4087,kontroll,WM983B
3674,1276.439286,12.916445,2.954721,203.032799,0.117782,0.295472,58.699956,0.0,0.0,2.0,56.689315,10.071547,1.024776,39.0,4088,kontroll,WM983B
3675,946.133389,10.775355,2.190124,277.074484,0.18204,0.219012,93.641667,0.0,0.0,2.0,58.72264,11.701469,1.039928,42.0,4089,kontroll,WM983B

In [5]:
file = path.joinpath('data', 'cell_line_profile.csv')
df_prof = pd.read_csv(file, sep=';')
df_prof = df_prof.drop('ID / plate', axis=1)
gr = ['cell line', 'type']
df_prof = df_prof.groupby(gr).mean() * 2.18  # (um)
# df_prof = df_prof.loc[df_[gr[0]].unique(),df_[gr[1]].unique(),:] 
df_prof

                           Area      Circ        AR     Round  Solidity
cell line type
A2058     1 uM      2895.178413  1.212703  6.976173  0.873557  1.881755
          2 uM      3645.282963  1.310624  6.554574  0.960169  1.952957
          kontroll  2953.229231  1.393590  5.878253  1.029094  1.964247
JL Post   1 uM      5292.694390  1.342614  4.268121  1.262512  1.876900
          2 uM      4600.158356  1.420106  4.570594  1.265236  1.893912
          kontroll  6146.417627  1.210048  4.805939  1.178974  1.754050
JR Post   1 uM      2808.415278  1.619377  4.691118  1.199091  2.065641
          2 uM      2808.255238  1.614999  4.634299  1.214260  2.038404
          kontroll  2210.607200  1.597853  4.391828  1.273905  1.995369
JR Pre    1 uM      3717.316765  1.655229  4.010110  1.327171  2.042468
          2 uM      3723.010606  1.694950  3.912968  1.335481  2.053494
          kontroll  3028.973750  1.610938  4.456574  1.225160  2.047674
WM983B    1 uM      2402.052958  1.621152  4.305408  1.291481  2.050643
          2 uM      2258.971268  1.643413  4.236354  1.237626  2.040357
          kontroll  2127.580909  1.521244  4.232866  1.252179  1.966955

In [6]:
# use only kontroll data
if ONLY_KONTROLL_DATA:
    gr = ['cell line']
    df_prof = df_prof.loc[(slice(None), 'kontroll'),:]
    display(df_prof)

In [7]:
df = pd.merge(df_, df_prof, on=gr, how='right')
profile = df[df_prof.columns]

In [8]:
labels = ['type', 'cell line', 'Cell ID unique'] 
x = df.drop(labels + list(profile.columns), axis=1)
y = df[labels]
y.drop_duplicates()

          type cell line Cell ID unique
0         1 uM     A2058              0
1         1 uM     A2058              3
2         1 uM     A2058              4
3         1 uM     A2058              5
4         1 uM     A2058              6
...        ...       ...            ...
3671  kontroll    WM983B           4085
3672  kontroll    WM983B           4086
3673  kontroll    WM983B           4087
3674  kontroll    WM983B           4088
3675  kontroll    WM983B           4089

[3676 rows x 3 columns]

In [9]:
x

,total_dist,dist std,dist mean,max_disp,directionality,avg speed,msd,angle from last_mov [deg] -- std,angle from last_mov [deg] -- mav,angle from last_mov [deg] -- zc,angle from init [deg] -- std,diff angle from init [deg] -- std,diff angle from init [deg] -- mav,diff angle from init [deg] -- zc
0,1552.005961,12.493506,3.592606,550.138021,0.297348,0.359261,238.315834,0.0,0.0,2.0,40.834526,13.582218,1.085205,72.0
1,2954.069092,16.607849,6.838123,554.637586,0.170457,0.683812,240.633322,0.0,0.0,2.0,96.197836,47.870355,9.87987,125.0
2,3491.190024,19.109881,8.081458,499.909698,0.132667,0.808146,174.137192,0.0,0.0,2.0,30.267191,5.650669,1.614578,133.0
3,1432.773708,11.643507,3.316606,285.105331,0.156835,0.331661,114.079129,0.0,0.0,2.0,80.227705,17.455075,2.446452,66.0
4,2708.524032,18.480233,6.269732,245.876555,0.065684,0.626973,98.168256,0.0,0.0,2.0,87.76583,19.463112,3.853848,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3671,1773.403827,14.840244,4.105101,117.19401,0.040715,0.41051,67.972264,0.0,0.0,2.0,89.582729,34.106675,6.052095,68.0
3672,181.737818,4.892592,0.420689,118.784997,0.42596,0.042069,17.678274,0.0,0.0,2.0,15.605693,9.970239,0.560451,8.0
3673,489.147555,5.657191,1.132286,76.796669,0.131983,0.113229,32.198044,0.0,0.0,2.0,80.125892,23.848899,3.175773,33.0
3674,1276.439286,12.916445,2.954721,203.032799,0.117782,0.295472,58.699956,0.0,0.0,2.0,56.689315,10.071547,1.024776,39.0
3675,946.133389,10.775355,2.190124,277.074484,0.18204,0.219012,93.641667,0.0,0.0,2.0,58.72264,11.701469,1.039928,42.0

In [10]:
f = x.copy()
dcols = x.columns

# normed with cell profile data
for col in dcols:
    for cell_par in profile.columns:
        f[f'{cell_par}_norm: {col}'] = f[col] / profile[cell_par]
            # break;
        # f[f'ContArea_norm: {tp}{col}'] = f[f'{tp}{col}'] / df_['cell size (um)'] * 2.18  # (um)

f

,total_dist,dist std,dist mean,max_disp,directionality,avg speed,msd,angle from last_mov [deg] -- std,angle from last_mov [deg] -- mav,angle from last_mov [deg] -- zc,...,Area_norm: diff angle from init [deg] -- mav,Circ_norm: diff angle from init [deg] -- mav,AR_norm: diff angle from init [deg] -- mav,Round_norm: diff angle from init [deg] -- mav,Solidity_norm: diff angle from init [deg] -- mav,Area_norm: diff angle from init [deg] -- zc,Circ_norm: diff angle from init [deg] -- zc,AR_norm: diff angle from init [deg] -- zc,Round_norm: diff angle from init [deg] -- zc,Solidity_norm: diff angle from init [deg] -- zc
0,1552.005961,12.493506,3.592606,550.138021,0.297348,0.359261,238.315834,0.0,0.0,2.0,...,0.000375,0.894864,0.155559,1.242282,0.576698,0.024869,59.37151,10.320845,82.421626,38.262149
1,2954.069092,16.607849,6.838123,554.637586,0.170457,0.683812,240.633322,0.0,0.0,2.0,...,0.003413,8.146984,1.416231,11.30993,5.250348,0.043175,103.075538,17.918134,143.0931,66.427343
2,3491.190024,19.109881,8.081458,499.909698,0.132667,0.808146,174.137192,0.0,0.0,2.0,...,0.000558,1.331388,0.231442,1.848279,0.858017,0.045938,109.672373,19.064894,152.251059,70.678693
3,1432.773708,11.643507,3.316606,285.105331,0.156835,0.331661,114.079129,0.0,0.0,2.0,...,0.000845,2.017355,0.350687,2.800563,1.30009,0.022797,54.423884,9.460775,75.553157,35.073637
4,2708.524032,18.480233,6.269732,245.876555,0.065684,0.626973,98.168256,0.0,0.0,2.0,...,0.001331,3.1779,0.55243,4.411672,2.048007,0.031086,74.214388,12.901056,103.027032,47.827687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3671,1773.403827,14.840244,4.105101,117.19401,0.040715,0.41051,67.972264,0.0,0.0,2.0,...,0.002845,3.978386,1.429786,4.833251,3.076886,0.031961,44.700269,16.064764,54.305344,34.571211
3672,181.737818,4.892592,0.420689,118.784997,0.42596,0.042069,17.678274,0.0,0.0,2.0,...,0.000263,0.368416,0.132405,0.447581,0.284933,0.00376,5.258855,1.889972,6.388864,4.067201
3673,489.147555,5.657191,1.132286,76.796669,0.131983,0.113229,32.198044,0.0,0.0,2.0,...,0.001493,2.087616,0.750265,2.536198,1.614564,0.015511,21.692778,7.796136,26.354064,16.777205
3674,1276.439286,12.916445,2.954721,203.032799,0.117782,0.295472,58.699956,0.0,0.0,2.0,...,0.000482,0.673643,0.2421,0.818394,0.520996,0.018331,25.636919,9.213615,31.145712,19.827606
3675,946.133389,10.775355,2.190124,277.074484,0.18204,0.219012,93.641667,0.0,0.0,2.0,...,0.000489,0.683604,0.245679,0.830495,0.5287,0.019741,27.60899,9.922354,33.541536,21.352807

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedShuffleSplit
# X = x
X = f
# X = f.drop(x.columns, axis=1)
X = X.fillna(0)

VERBOSE = False

REPEAT_CV = 10
selection = 15  # first n feature

# cv = StratifiedKFold(n_splits=5)
cv = StratifiedShuffleSplit(n_splits=5)
pipe = RandomForestClassifier(n_estimators=500, n_jobs=-2)
# pipe = make_pipeline(
#         # PCA(n_components=.97),
#         StandardScaler(),
#         RandomForestClassifier(n_estimators=500, n_jobs=-2)
# )
# pipe = get_ensemble_clf('voting', 'hard')

# print(X.isnull().values.any())
# with pd.option_context('display.max_rows', None):
#     display(X)
X

C:\Users\Csabi\AppData\Local\Temp\ipykernel_25108\4018361090.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.fillna(0)

,total_dist,dist std,dist mean,max_disp,directionality,avg speed,msd,angle from last_mov [deg] -- std,angle from last_mov [deg] -- mav,angle from last_mov [deg] -- zc,...,Area_norm: diff angle from init [deg] -- mav,Circ_norm: diff angle from init [deg] -- mav,AR_norm: diff angle from init [deg] -- mav,Round_norm: diff angle from init [deg] -- mav,Solidity_norm: diff angle from init [deg] -- mav,Area_norm: diff angle from init [deg] -- zc,Circ_norm: diff angle from init [deg] -- zc,AR_norm: diff angle from init [deg] -- zc,Round_norm: diff angle from init [deg] -- zc,Solidity_norm: diff angle from init [deg] -- zc
0,1552.005961,12.493506,3.592606,550.138021,0.297348,0.359261,238.315834,0.0,0.0,2.0,...,0.000375,0.894864,0.155559,1.242282,0.576698,0.024869,59.371510,10.320845,82.421626,38.262149
1,2954.069092,16.607849,6.838123,554.637586,0.170457,0.683812,240.633322,0.0,0.0,2.0,...,0.003413,8.146984,1.416231,11.309930,5.250348,0.043175,103.075538,17.918134,143.093100,66.427343
2,3491.190024,19.109881,8.081458,499.909698,0.132667,0.808146,174.137192,0.0,0.0,2.0,...,0.000558,1.331388,0.231442,1.848279,0.858017,0.045938,109.672373,19.064894,152.251059,70.678693
3,1432.773708,11.643507,3.316606,285.105331,0.156835,0.331661,114.079129,0.0,0.0,2.0,...,0.000845,2.017355,0.350687,2.800563,1.300090,0.022797,54.423884,9.460775,75.553157,35.073637
4,2708.524032,18.480233,6.269732,245.876555,0.065684,0.626973,98.168256,0.0,0.0,2.0,...,0.001331,3.177900,0.552430,4.411672,2.048007,0.031086,74.214388,12.901056,103.027032,47.827687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3671,1773.403827,14.840244,4.105101,117.194010,0.040715,0.410510,67.972264,0.0,0.0,2.0,...,0.002845,3.978386,1.429786,4.833251,3.076886,0.031961,44.700269,16.064764,54.305344,34.571211
3672,181.737818,4.892592,0.420689,118.784997,0.425960,0.042069,17.678274,0.0,0.0,2.0,...,0.000263,0.368416,0.132405,0.447581,0.284933,0.003760,5.258855,1.889972,6.388864,4.067201
3673,489.147555,5.657191,1.132286,76.796669,0.131983,0.113229,32.198044,0.0,0.0,2.0,...,0.001493,2.087616,0.750265,2.536198,1.614564,0.015511,21.692778,7.796136,26.354064,16.777205
3674,1276.439286,12.916445,2.954721,203.032799,0.117782,0.295472,58.699956,0.0,0.0,2.0,...,0.000482,0.673643,0.242100,0.818394,0.520996,0.018331,25.636919,9.213615,31.145712,19.827606
3675,946.133389,10.775355,2.190124,277.074484,0.182040,0.219012,93.641667,0.0,0.0,2.0,...,0.000489,0.683604,0.245679,0.830495,0.528700,0.019741,27.608990,9.922354,33.541536,21.352807

In [12]:
from utils import get_importance

imp = get_importance(X, y.drop('Cell ID unique', axis=1), sort=False, plot=True)

In [13]:
imp = imp.sort_values(ascending=False)
# display(imp)

most_imp = imp[:selection]
# most_imp = imp[imp > .005]

feat = most_imp.index

print(f'Selected features:\n{list(feat)}')
data = X[feat]

Selected features:
['Area_norm: angle from last_mov [deg] -- zc', 'AR_norm: angle from last_mov [deg] -- zc', 'Round_norm: angle from last_mov [deg] -- zc', 'Circ_norm: angle from last_mov [deg] -- zc', 'Solidity_norm: angle from last_mov [deg] -- zc', 'Area_norm: dist std', 'Area_norm: diff angle from init [deg] -- zc', 'AR_norm: diff angle from init [deg] -- zc', 'Round_norm: diff angle from init [deg] -- zc', 'AR_norm: dist std', 'Area_norm: avg speed', 'Area_norm: dist mean', 'Circ_norm: diff angle from init [deg] -- zc', 'Area_norm: total_dist', 'Area_norm: max_disp']

## Selecting best N features

In [14]:
from utils import make_cv

ver=VERBOSE

print(f'Investigate poison: {y["type"].unique()}')
for cell_line in y['cell line'].unique():
    if ver:
        print(f'\n======================================================')
    print(f'Investigation: {cell_line}')

    ind = (y['cell line'] == cell_line)
    
    make_cv(pipe, cv, data[ind].values, y[ind]['type'].values, y[ind]['Cell ID unique'], repeat=REPEAT_CV, verbose=ver)
print()

Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JL Post
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Post
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Pre
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: WM983B
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std

## Selecting features - one by one

In [15]:
ver=VERBOSE

for col in X.columns:
    data = X[[col]]
    print(f'\nColumn: {col}\n\n')
    
    print(f'Investigate poison: {y["type"].unique()}')
    for cell_line in y['cell line'].unique():
        if ver:
            print(f'\n======================================================')
        print(f'Investigation: {cell_line}')
    
        ind = (y['cell line'] == cell_line)
        make_cv(pipe, cv, data[ind].values, y[ind]['type'].values, y[ind]['Cell ID unique'],repeat=REPEAT_CV,  verbose=ver)
    print()

Column: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5632 +/- 0.0156 conf(0.95),	 0.0543 std
Investigation: JL Post
0.5531 +/- 0.0152 conf(0.95),	 0.0531 std
Investigation: JR Post
0.5795 +/- 0.0155 conf(0.95),	 0.0539 std
Investigation: JR Pre
0.5932 +/- 0.0129 conf(0.95),	 0.0449 std
Investigation: WM983B
0.5797 +/- 0.0133 conf(0.95),	 0.0464 std


Column: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5528 +/- 0.0136 conf(0.95),	 0.0475 std
Investigation: JL Post
0.5128 +/- 0.0188 conf(0.95),	 0.0653 std
Investigation: JR Post
0.5848 +/- 0.0162 conf(0.95),	 0.0563 std
Investigation: JR Pre
0.5874 +/- 0.0167 conf(0.95),	 0.0582 std
Investigation: WM983B
0.5767 +/- 0.0166 conf(0.95),	 0.0577 std


Column: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5650 +/- 0.0151 conf(0.95),	 0.0527 std
Investigation: JL Post
0.5423 +/- 0.0168 conf(0.95),	 0.0586 std
Investigation: JR Post
0.5985 +/- 0.0143 conf(0.95),	 0.0497 std
Investigation: JR Pre
0.6041 +/- 0.0162 conf(0.95),	 0.0564 std
Investigation: WM983B
0.5727 +/- 0.0121 conf(0.95),	 0.0421 std


Column: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5667 +/- 0.0140 conf(0.95),	 0.0488 std
Investigation: JL Post
0.4974 +/- 0.0159 conf(0.95),	 0.0555 std
Investigation: JR Post
0.5678 +/- 0.0146 conf(0.95),	 0.0510 std
Investigation: JR Pre
0.5885 +/- 0.0188 conf(0.95),	 0.0653 std
Investigation: WM983B
0.5563 +/- 0.0140 conf(0.95),	 0.0487 std


Column: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5475 +/- 0.0168 conf(0.95),	 0.0585 std
Investigation: JL Post
0.4902 +/- 0.0152 conf(0.95),	 0.0530 std
Investigation: JR Post
0.5238 +/- 0.0169 conf(0.95),	 0.0587 std
Investigation: JR Pre
0.5506 +/- 0.0160 conf(0.95),	 0.0557 std
Investigation: WM983B
0.5550 +/- 0.0155 conf(0.95),	 0.0540 std


Column: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5608 +/- 0.0161 conf(0.95),	 0.0561 std
Investigation: JL Post
0.5505 +/- 0.0165 conf(0.95),	 0.0574 std
Investigation: JR Post
0.5825 +/- 0.0134 conf(0.95),	 0.0467 std
Investigation: JR Pre
0.6079 +/- 0.0151 conf(0.95),	 0.0526 std
Investigation: WM983B
0.5805 +/- 0.0142 conf(0.95),	 0.0494 std


Column: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5948 +/- 0.0129 conf(0.95),	 0.0450 std
Investigation: JL Post
0.5036 +/- 0.0148 conf(0.95),	 0.0515 std
Investigation: JR Post
0.5896 +/- 0.0166 conf(0.95),	 0.0579 std
Investigation: JR Pre
0.5650 +/- 0.0173 conf(0.95),	 0.0604 std
Investigation: WM983B
0.5952 +/- 0.0137 conf(0.95),	 0.0476 std


Column: angle from last_mov [deg] -- std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.4125 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JL Post
0.3607 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Post
0.3671 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Pre
0.3971 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: WM983B
0.3500 +/- 0.0000 conf(0.95),	 0.0000 std


Column: angle from last_mov [deg] -- mav


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.4125 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JL Post
0.3607 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Post
0.3671 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Pre
0.3971 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: WM983B
0.3500 +/- 0.0000 conf(0.95),	 0.0000 std


Column: angle from last_mov [deg] -- zc


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.4125 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JL Post
0.3607 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Post
0.3671 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Pre
0.3971 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: WM983B
0.3500 +/- 0.0000 conf(0.95),	 0.0000 std


Column: angle from init [deg] -- std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5483 +/- 0.0136 conf(0.95),	 0.0474 std
Investigation: JL Post
0.5085 +/- 0.0162 conf(0.95),	 0.0563 std
Investigation: JR Post
0.5119 +/- 0.0157 conf(0.95),	 0.0545 std
Investigation: JR Pre
0.5621 +/- 0.0211 conf(0.95),	 0.0737 std
Investigation: WM983B
0.5417 +/- 0.0145 conf(0.95),	 0.0503 std


Column: diff angle from init [deg] -- std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5248 +/- 0.0165 conf(0.95),	 0.0574 std
Investigation: JL Post
0.5157 +/- 0.0149 conf(0.95),	 0.0518 std
Investigation: JR Post
0.5357 +/- 0.0191 conf(0.95),	 0.0666 std
Investigation: JR Pre
0.5794 +/- 0.0155 conf(0.95),	 0.0541 std
Investigation: WM983B
0.5298 +/- 0.0140 conf(0.95),	 0.0486 std


Column: diff angle from init [deg] -- mav


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5468 +/- 0.0136 conf(0.95),	 0.0473 std
Investigation: JL Post
0.5269 +/- 0.0181 conf(0.95),	 0.0632 std
Investigation: JR Post
0.5357 +/- 0.0146 conf(0.95),	 0.0510 std
Investigation: JR Pre
0.6018 +/- 0.0144 conf(0.95),	 0.0503 std
Investigation: WM983B
0.5350 +/- 0.0136 conf(0.95),	 0.0473 std


Column: diff angle from init [deg] -- zc


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5195 +/- 0.0115 conf(0.95),	 0.0402 std
Investigation: JL Post
0.5508 +/- 0.0171 conf(0.95),	 0.0595 std
Investigation: JR Post
0.5613 +/- 0.0135 conf(0.95),	 0.0471 std
Investigation: JR Pre
0.5106 +/- 0.0151 conf(0.95),	 0.0525 std
Investigation: WM983B
0.4618 +/- 0.0144 conf(0.95),	 0.0503 std


Column: Area_norm: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6660 +/- 0.0139 conf(0.95),	 0.0485 std
Investigation: JL Post
0.6148 +/- 0.0193 conf(0.95),	 0.0671 std
Investigation: JR Post
0.6291 +/- 0.0145 conf(0.95),	 0.0504 std
Investigation: JR Pre
0.6600 +/- 0.0154 conf(0.95),	 0.0536 std
Investigation: WM983B
0.6422 +/- 0.0126 conf(0.95),	 0.0439 std


Column: Circ_norm: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6210 +/- 0.0167 conf(0.95),	 0.0583 std
Investigation: JL Post
0.6397 +/- 0.0175 conf(0.95),	 0.0611 std
Investigation: JR Post
0.6608 +/- 0.0134 conf(0.95),	 0.0467 std
Investigation: JR Pre
0.6988 +/- 0.0143 conf(0.95),	 0.0498 std
Investigation: WM983B
0.6678 +/- 0.0139 conf(0.95),	 0.0485 std


Column: AR_norm: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6412 +/- 0.0147 conf(0.95),	 0.0511 std
Investigation: JL Post
0.6528 +/- 0.0177 conf(0.95),	 0.0617 std
Investigation: JR Post
0.6891 +/- 0.0148 conf(0.95),	 0.0516 std
Investigation: JR Pre
0.6435 +/- 0.0162 conf(0.95),	 0.0563 std
Investigation: WM983B
0.6380 +/- 0.0133 conf(0.95),	 0.0462 std


Column: Round_norm: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6245 +/- 0.0134 conf(0.95),	 0.0468 std
Investigation: JL Post
0.6239 +/- 0.0189 conf(0.95),	 0.0659 std
Investigation: JR Post
0.6522 +/- 0.0155 conf(0.95),	 0.0538 std
Investigation: JR Pre
0.6756 +/- 0.0161 conf(0.95),	 0.0561 std
Investigation: WM983B
0.6342 +/- 0.0131 conf(0.95),	 0.0456 std


Column: Solidity_norm: total_dist


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6357 +/- 0.0130 conf(0.95),	 0.0453 std
Investigation: JL Post
0.6492 +/- 0.0151 conf(0.95),	 0.0525 std
Investigation: JR Post
0.6648 +/- 0.0152 conf(0.95),	 0.0530 std
Investigation: JR Pre
0.6603 +/- 0.0157 conf(0.95),	 0.0546 std
Investigation: WM983B
0.6310 +/- 0.0142 conf(0.95),	 0.0496 std


Column: Area_norm: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6753 +/- 0.0142 conf(0.95),	 0.0494 std
Investigation: JL Post
0.5544 +/- 0.0149 conf(0.95),	 0.0518 std
Investigation: JR Post
0.6463 +/- 0.0150 conf(0.95),	 0.0524 std
Investigation: JR Pre
0.6732 +/- 0.0147 conf(0.95),	 0.0513 std
Investigation: WM983B
0.6593 +/- 0.0136 conf(0.95),	 0.0474 std


Column: Circ_norm: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6350 +/- 0.0156 conf(0.95),	 0.0544 std
Investigation: JL Post
0.6128 +/- 0.0199 conf(0.95),	 0.0693 std
Investigation: JR Post
0.6635 +/- 0.0133 conf(0.95),	 0.0465 std
Investigation: JR Pre
0.6676 +/- 0.0139 conf(0.95),	 0.0484 std
Investigation: WM983B
0.6458 +/- 0.0164 conf(0.95),	 0.0570 std


Column: AR_norm: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6412 +/- 0.0147 conf(0.95),	 0.0513 std
Investigation: JL Post
0.5856 +/- 0.0183 conf(0.95),	 0.0639 std
Investigation: JR Post
0.6851 +/- 0.0131 conf(0.95),	 0.0458 std
Investigation: JR Pre
0.6544 +/- 0.0172 conf(0.95),	 0.0599 std
Investigation: WM983B
0.6417 +/- 0.0147 conf(0.95),	 0.0512 std


Column: Round_norm: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6040 +/- 0.0156 conf(0.95),	 0.0543 std
Investigation: JL Post
0.6052 +/- 0.0160 conf(0.95),	 0.0558 std
Investigation: JR Post
0.6706 +/- 0.0129 conf(0.95),	 0.0448 std
Investigation: JR Pre
0.6665 +/- 0.0153 conf(0.95),	 0.0533 std
Investigation: WM983B
0.6190 +/- 0.0170 conf(0.95),	 0.0592 std


Column: Solidity_norm: dist std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6043 +/- 0.0143 conf(0.95),	 0.0499 std
Investigation: JL Post
0.6069 +/- 0.0182 conf(0.95),	 0.0635 std
Investigation: JR Post
0.6684 +/- 0.0127 conf(0.95),	 0.0442 std
Investigation: JR Pre
0.6729 +/- 0.0151 conf(0.95),	 0.0527 std
Investigation: WM983B
0.6477 +/- 0.0112 conf(0.95),	 0.0389 std


Column: Area_norm: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6708 +/- 0.0146 conf(0.95),	 0.0507 std
Investigation: JL Post
0.5908 +/- 0.0139 conf(0.95),	 0.0485 std
Investigation: JR Post
0.6243 +/- 0.0136 conf(0.95),	 0.0473 std
Investigation: JR Pre
0.6335 +/- 0.0162 conf(0.95),	 0.0563 std
Investigation: WM983B
0.6250 +/- 0.0168 conf(0.95),	 0.0585 std


Column: Circ_norm: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6298 +/- 0.0159 conf(0.95),	 0.0554 std
Investigation: JL Post
0.6528 +/- 0.0161 conf(0.95),	 0.0562 std
Investigation: JR Post
0.6663 +/- 0.0133 conf(0.95),	 0.0463 std
Investigation: JR Pre
0.6974 +/- 0.0180 conf(0.95),	 0.0627 std
Investigation: WM983B
0.6675 +/- 0.0118 conf(0.95),	 0.0412 std


Column: AR_norm: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6623 +/- 0.0148 conf(0.95),	 0.0515 std
Investigation: JL Post
0.6403 +/- 0.0156 conf(0.95),	 0.0542 std
Investigation: JR Post
0.6876 +/- 0.0146 conf(0.95),	 0.0508 std
Investigation: JR Pre
0.6412 +/- 0.0171 conf(0.95),	 0.0595 std
Investigation: WM983B
0.6440 +/- 0.0147 conf(0.95),	 0.0511 std


Column: Round_norm: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6080 +/- 0.0172 conf(0.95),	 0.0599 std
Investigation: JL Post
0.6105 +/- 0.0136 conf(0.95),	 0.0473 std
Investigation: JR Post
0.6592 +/- 0.0133 conf(0.95),	 0.0464 std
Investigation: JR Pre
0.6682 +/- 0.0160 conf(0.95),	 0.0557 std
Investigation: WM983B
0.6400 +/- 0.0112 conf(0.95),	 0.0390 std


Column: Solidity_norm: dist mean


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6520 +/- 0.0154 conf(0.95),	 0.0536 std
Investigation: JL Post
0.6243 +/- 0.0151 conf(0.95),	 0.0524 std
Investigation: JR Post
0.6709 +/- 0.0138 conf(0.95),	 0.0480 std
Investigation: JR Pre
0.6488 +/- 0.0136 conf(0.95),	 0.0472 std
Investigation: WM983B
0.6378 +/- 0.0130 conf(0.95),	 0.0454 std


Column: Area_norm: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6800 +/- 0.0119 conf(0.95),	 0.0415 std
Investigation: JL Post
0.5748 +/- 0.0151 conf(0.95),	 0.0525 std
Investigation: JR Post
0.6301 +/- 0.0140 conf(0.95),	 0.0488 std
Investigation: JR Pre
0.6591 +/- 0.0156 conf(0.95),	 0.0543 std
Investigation: WM983B
0.6703 +/- 0.0142 conf(0.95),	 0.0496 std


Column: Circ_norm: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6512 +/- 0.0148 conf(0.95),	 0.0516 std
Investigation: JL Post
0.5633 +/- 0.0170 conf(0.95),	 0.0594 std
Investigation: JR Post
0.6587 +/- 0.0149 conf(0.95),	 0.0519 std
Investigation: JR Pre
0.6494 +/- 0.0156 conf(0.95),	 0.0543 std
Investigation: WM983B
0.6775 +/- 0.0166 conf(0.95),	 0.0577 std


Column: AR_norm: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6262 +/- 0.0148 conf(0.95),	 0.0514 std
Investigation: JL Post
0.5849 +/- 0.0186 conf(0.95),	 0.0649 std
Investigation: JR Post
0.6765 +/- 0.0169 conf(0.95),	 0.0588 std
Investigation: JR Pre
0.6279 +/- 0.0161 conf(0.95),	 0.0562 std
Investigation: WM983B
0.6660 +/- 0.0148 conf(0.95),	 0.0515 std


Column: Round_norm: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6405 +/- 0.0162 conf(0.95),	 0.0564 std
Investigation: JL Post
0.5630 +/- 0.0173 conf(0.95),	 0.0604 std
Investigation: JR Post
0.6706 +/- 0.0136 conf(0.95),	 0.0473 std
Investigation: JR Pre
0.6679 +/- 0.0199 conf(0.95),	 0.0695 std
Investigation: WM983B
0.6585 +/- 0.0155 conf(0.95),	 0.0541 std


Column: Solidity_norm: max_disp


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6380 +/- 0.0129 conf(0.95),	 0.0451 std
Investigation: JL Post
0.5993 +/- 0.0144 conf(0.95),	 0.0502 std
Investigation: JR Post
0.6785 +/- 0.0153 conf(0.95),	 0.0535 std
Investigation: JR Pre
0.6703 +/- 0.0175 conf(0.95),	 0.0611 std
Investigation: WM983B
0.6805 +/- 0.0128 conf(0.95),	 0.0446 std


Column: Area_norm: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5043 +/- 0.0158 conf(0.95),	 0.0549 std
Investigation: JL Post
0.4866 +/- 0.0188 conf(0.95),	 0.0654 std
Investigation: JR Post
0.4532 +/- 0.0137 conf(0.95),	 0.0478 std
Investigation: JR Pre
0.4541 +/- 0.0170 conf(0.95),	 0.0592 std
Investigation: WM983B
0.5245 +/- 0.0130 conf(0.95),	 0.0451 std


Column: Circ_norm: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6098 +/- 0.0175 conf(0.95),	 0.0610 std
Investigation: JL Post
0.6138 +/- 0.0169 conf(0.95),	 0.0589 std
Investigation: JR Post
0.5785 +/- 0.0153 conf(0.95),	 0.0532 std
Investigation: JR Pre
0.6515 +/- 0.0157 conf(0.95),	 0.0546 std
Investigation: WM983B
0.6013 +/- 0.0135 conf(0.95),	 0.0472 std


Column: AR_norm: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5813 +/- 0.0160 conf(0.95),	 0.0556 std
Investigation: JL Post
0.6039 +/- 0.0175 conf(0.95),	 0.0609 std
Investigation: JR Post
0.6157 +/- 0.0153 conf(0.95),	 0.0533 std
Investigation: JR Pre
0.6553 +/- 0.0183 conf(0.95),	 0.0638 std
Investigation: WM983B
0.6293 +/- 0.0150 conf(0.95),	 0.0522 std


Column: Round_norm: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6128 +/- 0.0146 conf(0.95),	 0.0508 std
Investigation: JL Post
0.5734 +/- 0.0152 conf(0.95),	 0.0528 std
Investigation: JR Post
0.5866 +/- 0.0119 conf(0.95),	 0.0413 std
Investigation: JR Pre
0.6315 +/- 0.0175 conf(0.95),	 0.0611 std
Investigation: WM983B
0.6100 +/- 0.0147 conf(0.95),	 0.0514 std


Column: Solidity_norm: directionality


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.5945 +/- 0.0134 conf(0.95),	 0.0466 std
Investigation: JL Post
0.5718 +/- 0.0165 conf(0.95),	 0.0576 std
Investigation: JR Post
0.5924 +/- 0.0136 conf(0.95),	 0.0473 std
Investigation: JR Pre
0.6121 +/- 0.0169 conf(0.95),	 0.0588 std
Investigation: WM983B
0.6123 +/- 0.0136 conf(0.95),	 0.0473 std


Column: Area_norm: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6175 +/- 0.0140 conf(0.95),	 0.0487 std
Investigation: JL Post
0.5600 +/- 0.0187 conf(0.95),	 0.0652 std
Investigation: JR Post
0.6099 +/- 0.0127 conf(0.95),	 0.0442 std
Investigation: JR Pre
0.6082 +/- 0.0181 conf(0.95),	 0.0631 std
Investigation: WM983B
0.5780 +/- 0.0145 conf(0.95),	 0.0506 std


Column: Circ_norm: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6302 +/- 0.0146 conf(0.95),	 0.0509 std
Investigation: JL Post
0.6384 +/- 0.0139 conf(0.95),	 0.0486 std
Investigation: JR Post
0.6549 +/- 0.0139 conf(0.95),	 0.0486 std
Investigation: JR Pre
0.7147 +/- 0.0144 conf(0.95),	 0.0502 std
Investigation: WM983B
0.6570 +/- 0.0147 conf(0.95),	 0.0514 std


Column: AR_norm: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6542 +/- 0.0147 conf(0.95),	 0.0513 std
Investigation: JL Post
0.6433 +/- 0.0177 conf(0.95),	 0.0617 std
Investigation: JR Post
0.6881 +/- 0.0137 conf(0.95),	 0.0477 std
Investigation: JR Pre
0.6326 +/- 0.0185 conf(0.95),	 0.0646 std
Investigation: WM983B
0.6488 +/- 0.0146 conf(0.95),	 0.0508 std


Column: Round_norm: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6232 +/- 0.0157 conf(0.95),	 0.0546 std
Investigation: JL Post
0.5905 +/- 0.0176 conf(0.95),	 0.0614 std
Investigation: JR Post
0.6499 +/- 0.0126 conf(0.95),	 0.0437 std
Investigation: JR Pre
0.6712 +/- 0.0131 conf(0.95),	 0.0457 std
Investigation: WM983B
0.6360 +/- 0.0138 conf(0.95),	 0.0479 std


Column: Solidity_norm: avg speed


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6445 +/- 0.0161 conf(0.95),	 0.0560 std
Investigation: JL Post
0.6430 +/- 0.0194 conf(0.95),	 0.0676 std
Investigation: JR Post
0.6562 +/- 0.0140 conf(0.95),	 0.0489 std
Investigation: JR Pre
0.6488 +/- 0.0145 conf(0.95),	 0.0507 std
Investigation: WM983B
0.6348 +/- 0.0167 conf(0.95),	 0.0581 std


Column: Area_norm: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.7007 +/- 0.0162 conf(0.95),	 0.0564 std
Investigation: JL Post
0.5820 +/- 0.0150 conf(0.95),	 0.0522 std
Investigation: JR Post
0.6468 +/- 0.0133 conf(0.95),	 0.0465 std
Investigation: JR Pre
0.6400 +/- 0.0165 conf(0.95),	 0.0576 std
Investigation: WM983B
0.6388 +/- 0.0128 conf(0.95),	 0.0445 std


Column: Circ_norm: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6782 +/- 0.0174 conf(0.95),	 0.0605 std
Investigation: JL Post
0.5810 +/- 0.0156 conf(0.95),	 0.0543 std
Investigation: JR Post
0.6600 +/- 0.0151 conf(0.95),	 0.0527 std
Investigation: JR Pre
0.6535 +/- 0.0149 conf(0.95),	 0.0518 std
Investigation: WM983B
0.6538 +/- 0.0128 conf(0.95),	 0.0445 std


Column: AR_norm: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6795 +/- 0.0129 conf(0.95),	 0.0449 std
Investigation: JL Post
0.5570 +/- 0.0155 conf(0.95),	 0.0539 std
Investigation: JR Post
0.6643 +/- 0.0147 conf(0.95),	 0.0513 std
Investigation: JR Pre
0.6726 +/- 0.0171 conf(0.95),	 0.0595 std
Investigation: WM983B
0.6315 +/- 0.0155 conf(0.95),	 0.0539 std


Column: Round_norm: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.6708 +/- 0.0148 conf(0.95),	 0.0515 std
Investigation: JL Post
0.5511 +/- 0.0182 conf(0.95),	 0.0633 std
Investigation: JR Post
0.6484 +/- 0.0139 conf(0.95),	 0.0483 std
Investigation: JR Pre
0.6456 +/- 0.0150 conf(0.95),	 0.0521 std
Investigation: WM983B
0.6240 +/- 0.0133 conf(0.95),	 0.0462 std


Column: Solidity_norm: msd


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.7027 +/- 0.0161 conf(0.95),	 0.0563 std
Investigation: JL Post
0.5590 +/- 0.0166 conf(0.95),	 0.0579 std
Investigation: JR Post
0.6716 +/- 0.0141 conf(0.95),	 0.0491 std
Investigation: JR Pre
0.6482 +/- 0.0178 conf(0.95),	 0.0619 std
Investigation: WM983B
0.6570 +/- 0.0121 conf(0.95),	 0.0423 std


Column: Area_norm: angle from last_mov [deg] -- std


Investigate poison: ['1 uM' '2 uM' 'kontroll']
Investigation: A2058
0.4125 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JL Post
0.3607 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Post
0.3671 +/- 0.0000 conf(0.95),	 0.0000 std
Investigation: JR Pre

## Kontroll classification

In [16]:
ver=VERBOSE
print(f'Investigate Controlls: {y["cell line"].unique()}')


ind = y['type'] == 'kontroll'

make_cv(pipe, cv, data[ind].values, y[ind]['cell line'].values, y[ind]['Cell ID unique'], repeat=REPEAT_CV, verbose=ver)

Investigate Controlls: ['A2058' 'JL Post' 'JR Post' 'JR Pre' 'WM983B']
0.8186 +/- 0.0078 conf(0.95),	 0.0273 std

In [17]:
ver=VERBOSE
print(f'Investigate Controlls: {y["cell line"].unique()} - all features')


ind = y['type'] == 'kontroll'

make_cv(pipe, cv, X[ind].values, y[ind]['cell line'].values, y[ind]['Cell ID unique'], repeat=REPEAT_CV, verbose=ver)

Investigate Controlls: ['A2058' 'JL Post' 'JR Post' 'JR Pre' 'WM983B'] - all features
1.0000 +/- 0.0000 conf(0.95),	 0.0000 std

In [18]:
# ver=VERBOSE

# # print(f'Investigation for top {selection} feature by method.')

# # print(f'Investigate poison: {y["type"].unique()}')
# for method in y['investigation'].unique():
#     feat = get_importance(X, y, plot=True)[:selection].index
#     print(f'\n{method} - Selected features:\n{list(feat)}\n')
#     # data = X[feat]
    
#     # for cell_line in y[y['investigation']==method]['cell line'].unique():
#     #     if ver:
#     #         print(f'\n======================================================')
#     #     print(f'Investigation: {method}-{cell_line}')

#     #     ind = (y['investigation'] == method) & (y['cell line'] == cell_line)
        
#     #     make_cv(pipe, cv, data[ind].values, y[ind]['type'].values, verbose=ver)